namespace SchemaGenerator.Models;

/// <summary>
/// Represents the complete schema of a SQL Server database including all tables and their relationships.
/// Generated by scanning the database metadata and used as context for LLM query generation.
/// </summary>
public class DatabaseSchema
{
    /// <summary>
    /// The name of the database (e.g., "Chinook", "AdventureWorks").
    /// </summary>
    public string DatabaseName { get; set; } = string.Empty;
    
    /// <summary>
    /// The SQL Server instance name (e.g., "(localdb)\MSSQLLocalDB", "localhost").
    /// </summary>
    public string ServerName { get; set; } = string.Empty;
    
    /// <summary>
    /// Timestamp when this schema was generated.
    /// Used to track freshness and detect schema drift.
    /// </summary>
    public DateTime GeneratedAt { get; set; }
    
    /// <summary>
    /// Collection of all tables in the database with their columns, keys, and relationships.
    /// </summary>
    public List<TableSchema> Tables { get; set; } = new();
}
